**Regras de associação**

**Algoritmo Apriori**

**Veja: https://www.youtube.com/watch?v=0v6PiOpsJi8**

In [49]:
!pip install apyori

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: apyori in /usr/local/lib/python3.7/dist-packages (1.1.2)

In [50]:
import pandas as pd
from apyori import apriori

In [51]:
#encoding = "cp1252", encoding='utf-8', encoding='latin1'etc
base= pd.read_csv('/content/sample_data/MercadoSim.csv', ';',header=None)
base

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)

       0     1        2    3         4      5       6
0    NaN  Cafe      NaN  Pao  Manteiga    NaN     NaN
1  Leite   NaN  Cerveja  Pao  Manteiga    NaN     NaN
2    NaN  Cafe      NaN  Pao  Manteiga    NaN     NaN
3  Leite  Cafe      NaN  Pao  Manteiga    NaN     NaN
4    NaN   NaN  Cerveja  NaN       NaN    NaN     NaN
5    NaN   NaN      NaN  NaN  Manteiga    NaN     NaN
6    NaN   NaN      NaN  Pao       NaN    NaN     NaN
7    NaN   NaN      NaN  NaN       NaN    NaN  Feijao
8    NaN   NaN      NaN  NaN       NaN  Arroz  Feijao
9    NaN   NaN      NaN  NaN       NaN  Arroz     NaN

In [52]:
base.shape

(10, 7)

**Como estaremos treinando um modelo a priori, que recebe entradas em formato de lista, precisamos transformar o dataframe em uma lista de transações.**

In [53]:
transacoes = []
for i in range(len(base)):
  #print(i)
  #print(base_mercado1.values[i, 0])
  transacoes.append([str(base.values[i, j]) for j in range(base.shape[1])])

In [54]:
transacoes

[['nan', 'Cafe', 'nan', 'Pao', 'Manteiga', 'nan', 'nan'],
 ['Leite', 'nan', 'Cerveja', 'Pao', 'Manteiga', 'nan', 'nan'],
 ['nan', 'Cafe', 'nan', 'Pao', 'Manteiga', 'nan', 'nan'],
 ['Leite', 'Cafe', 'nan', 'Pao', 'Manteiga', 'nan', 'nan'],
 ['nan', 'nan', 'Cerveja', 'nan', 'nan', 'nan', 'nan'],
 ['nan', 'nan', 'nan', 'nan', 'Manteiga', 'nan', 'nan'],
 ['nan', 'nan', 'nan', 'Pao', 'nan', 'nan', 'nan'],
 ['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Feijao'],
 ['nan', 'nan', 'nan', 'nan', 'nan', 'Arroz', 'Feijao'],
 ['nan', 'nan', 'nan', 'nan', 'nan', 'Arroz', 'nan']]

In [55]:
type(transacoes)

list

**Vamos chamar executar o algoritmo apriori e armazenar as regras obtidas**

In [56]:
regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8)
saida = list(regras) 
print(len(saida))
print(saida)

12
[RelationRecord(items=frozenset({'nan'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'Manteiga', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'Cafe', 'Pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'Cafe', 'nan'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'Manteiga', 'Pao'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Manteiga'}), items_add=frozenset({'Pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'Pao'}), items_add=frozenset({'Manteiga'}), confidence=0.8, lift=1.6)]), RelationRecord(items=frozenset({'Manteiga', 'nan'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Manteiga'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'nan', 'Pao'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Pao'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'Manteiga', 'Cafe', 'Pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga', 'Pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Cafe', 'Pao'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'Manteiga', 'Cafe', 'nan'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga', 'nan'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'Cafe', 'nan'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'Cafe', 'nan', 'Pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'nan', 'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Cafe', 'Pao'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'Cafe', 'nan'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'Manteiga', 'nan', 'Pao'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Manteiga'}), items_add=frozenset({'nan', 'Pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'Pao'}), items_add=frozenset({'Manteiga', 'nan'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'Manteiga', 'Pao'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'Manteiga', 'nan'}), items_add=frozenset({'Pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'nan', 'Pao'}), items_add=frozenset({'Manteiga'}), confidence=0.8, lift=1.6)]), RelationRecord(items=frozenset({'Manteiga', 'Cafe', 'nan', 'Pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga', 'nan', 'Pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe'}), items_add=frozenset({'nan', 'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Cafe', 'Pao'}), items_add=frozenset({'Manteiga', 'nan'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Cafe', 'nan'}), items_add=frozenset({'Manteiga', 'Pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe', 'Pao'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe', 'nan'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Cafe', 'nan', 'Pao'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)])]

In [57]:
print(saida[0])

RelationRecord(items=frozenset({'nan'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0)])

In [58]:
print(saida[1])

RelationRecord(items=frozenset({'Manteiga', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)])

In [59]:
print(saida[2])

RelationRecord(items=frozenset({'Cafe', 'Pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0)])

**Para facilitar a visualização, veja como transformar isso em um dataframe** 

Extraído de:

https://www.section.io/engineering-education/apriori-algorithm-in-python/

https://splunktool.com/understanding-apyoris-output

In [60]:
lhs = []
rhs = []
suporte = []
confianca = []
lift = []

for resultado in saida:
  #print(resultado)
  s = resultado[1]
  #print(s)
  result_rules = resultado[2]
  #print(result_rule)
  for result_rule in result_rules:
    #print(result_rule)
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    #print(a, ' - ', b, ' - ', c, ' - ', l)
    lhs.append(a)
    rhs.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(l)
    RegrasFinais = pd.DataFrame({'Lhs': lhs, 'Rhs': rhs, 'suporte': suporte, 'confianca': confianca, 'lift': lift})

In [61]:
RegrasFinais

                      Lhs                   Rhs  suporte  confianca  lift
0                      []                 [nan]      1.0        1.0   1.0
1                  [Cafe]            [Manteiga]      0.3        1.0   2.0
2                  [Cafe]                 [Pao]      0.3        1.0   2.0
3                  [Cafe]                 [nan]      0.3        1.0   1.0
4              [Manteiga]                 [Pao]      0.4        0.8   1.6
5                   [Pao]            [Manteiga]      0.4        0.8   1.6
6              [Manteiga]                 [nan]      0.5        1.0   1.0
7                   [Pao]                 [nan]      0.5        1.0   1.0
8                  [Cafe]       [Manteiga, Pao]      0.3        1.0   2.5
9        [Manteiga, Cafe]                 [Pao]      0.3        1.0   2.0
10            [Cafe, Pao]            [Manteiga]      0.3        1.0   2.0
11                 [Cafe]       [Manteiga, nan]      0.3        1.0   2.0
12       [Manteiga, Cafe]                 [nan]      0.3        1.0   1.0
13            [Cafe, nan]            [Manteiga]      0.3        1.0   2.0
14                 [Cafe]            [nan, Pao]      0.3        1.0   2.0
15            [Cafe, Pao]                 [nan]      0.3        1.0   1.0
16            [Cafe, nan]                 [Pao]      0.3        1.0   2.0
17             [Manteiga]            [nan, Pao]      0.4        0.8   1.6
18                  [Pao]       [Manteiga, nan]      0.4        0.8   1.6
19        [Manteiga, Pao]                 [nan]      0.4        1.0   1.0
20        [Manteiga, nan]                 [Pao]      0.4        0.8   1.6
21             [nan, Pao]            [Manteiga]      0.4        0.8   1.6
22                 [Cafe]  [Manteiga, nan, Pao]      0.3        1.0   2.5
23       [Manteiga, Cafe]            [nan, Pao]      0.3        1.0   2.0
24            [Cafe, Pao]       [Manteiga, nan]      0.3        1.0   2.0
25            [Cafe, nan]       [Manteiga, Pao]      0.3        1.0   2.5
26  [Manteiga, Cafe, Pao]                 [nan]      0.3        1.0   1.0
27  [Manteiga, Cafe, nan]                 [Pao]      0.3        1.0   2.0
28       [Cafe, nan, Pao]            [Manteiga]      0.3        1.0   2.0

**Podemos ordenar estas regras por uma métrica desejada**

In [62]:
RegrasFinais.sort_values(by='lift', ascending =False)

                      Lhs                   Rhs  suporte  confianca  lift
25            [Cafe, nan]       [Manteiga, Pao]      0.3        1.0   2.5
22                 [Cafe]  [Manteiga, nan, Pao]      0.3        1.0   2.5
8                  [Cafe]       [Manteiga, Pao]      0.3        1.0   2.5
14                 [Cafe]            [nan, Pao]      0.3        1.0   2.0
11                 [Cafe]       [Manteiga, nan]      0.3        1.0   2.0
27  [Manteiga, Cafe, nan]                 [Pao]      0.3        1.0   2.0
24            [Cafe, Pao]       [Manteiga, nan]      0.3        1.0   2.0
23       [Manteiga, Cafe]            [nan, Pao]      0.3        1.0   2.0
16            [Cafe, nan]                 [Pao]      0.3        1.0   2.0
1                  [Cafe]            [Manteiga]      0.3        1.0   2.0
13            [Cafe, nan]            [Manteiga]      0.3        1.0   2.0
28       [Cafe, nan, Pao]            [Manteiga]      0.3        1.0   2.0
9        [Manteiga, Cafe]                 [Pao]      0.3        1.0   2.0
2                  [Cafe]                 [Pao]      0.3        1.0   2.0
10            [Cafe, Pao]            [Manteiga]      0.3        1.0   2.0
20        [Manteiga, nan]                 [Pao]      0.4        0.8   1.6
5                   [Pao]            [Manteiga]      0.4        0.8   1.6
17             [Manteiga]            [nan, Pao]      0.4        0.8   1.6
18                  [Pao]       [Manteiga, nan]      0.4        0.8   1.6
21             [nan, Pao]            [Manteiga]      0.4        0.8   1.6
4              [Manteiga]                 [Pao]      0.4        0.8   1.6
26  [Manteiga, Cafe, Pao]                 [nan]      0.3        1.0   1.0
3                  [Cafe]                 [nan]      0.3        1.0   1.0
12       [Manteiga, Cafe]                 [nan]      0.3        1.0   1.0
6              [Manteiga]                 [nan]      0.5        1.0   1.0
19        [Manteiga, Pao]                 [nan]      0.4        1.0   1.0
7                   [Pao]                 [nan]      0.5        1.0   1.0
15            [Cafe, Pao]                 [nan]      0.3        1.0   1.0
0                      []                 [nan]      1.0        1.0   1.0